// <auto-generated />
using System;
using AdventureWorks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdventureWorks.Migrations
{
    [DbContext(typeof(AdventureWorksContext))]
    partial class AdventureWorksContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Production")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.BillOfMaterials", b =>
                {
                    b.Property<int>("BillOfMaterialsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillOfMaterialsId"));

                    b.Property<int>("BOMLevel")
                        .HasColumnType("int");

                    b.Property<int>("ComponentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ProductAssemblyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnitMeasureCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("perassemblyqty")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BillOfMaterialsId");

                    b.HasIndex("ProductAssemblyId");

                    b.HasIndex("UnitMeasureCode");

                    b.ToTable("BillOfMaterials", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Culture", b =>
                {
                    b.Property<string>("CultureId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CultureId");

                    b.ToTable("Culture", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Document", b =>
                {
                    b.Property<string>("DocumentNode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Revision")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentNode");

                    b.ToTable("Document", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Illustration", b =>
                {
                    b.Property<int>("IllustrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IllustrationId"));

                    b.Property<string>("Diagram")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("IllustrationId");

                    b.ToTable("Illustration", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Location", b =>
                {
                    b.Property<short>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("LocationId"));

                    b.Property<decimal>("Availability")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("CostRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Location", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Color")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DaysToManufacture")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DiscontinuedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FinishedGoodsFlag")
                        .HasColumnType("bit");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("MakeFlag")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductLine")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductModelId")
                        .HasColumnType("int");

                    b.Property<string>("ProductNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductSubcategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("Rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("SellEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SellStartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SizeUnitMeasureCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StandardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Style")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeightUnitMeasureCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("ProductModelId");

                    b.HasIndex("ProductSubcategoryId")
                        .IsUnique()
                        .HasFilter("[ProductSubcategoryId] IS NOT NULL");

                    b.ToTable("Product", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductCategory", b =>
                {
                    b.Property<int>("ProductCategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCategoryId"));

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductCategoryId");

                    b.ToTable("ProductCategory", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductCostHistory", b =>
                {
                    b.Property<int>("ProductCostHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductCostHistoryId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<decimal>("StandardCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductCostHistoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductCostHistory", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductDescription", b =>
                {
                    b.Property<int>("ProductDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDescriptionId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductDescriptionId");

                    b.ToTable("ProductDescription", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductDocument", b =>
                {
                    b.Property<int>("ProductDocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductDocumentId"));

                    b.Property<string>("DocumentNode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DocumentNodeNavigationDocumentNode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("ProductDocumentId");

                    b.HasIndex("DocumentNodeNavigationDocumentNode");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductDocument", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductInventory", b =>
                {
                    b.Property<int>("ProductInventoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductInventoryId"));

                    b.Property<byte>("Bin")
                        .HasColumnType("tinyint");

                    b.Property<short>("LocationId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<short>("Quantity")
                        .HasColumnType("smallint");

                    b.Property<Guid>("Rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductInventoryId");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductInventory", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductListPriceHistory", b =>
                {
                    b.Property<int>("ProductListPriceHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductListPriceHistoryId"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ListPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ProductListPriceHistoryId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductListPriceHistory", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductModel", b =>
                {
                    b.Property<int>("ProductModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductModelId"));

                    b.Property<string>("CatalogDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("Rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductModelId");

                    b.ToTable("ProductModel", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductModelIllustration", b =>
                {
                    b.Property<int>("ProductModelIllustrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductModelIllustrationId"));

                    b.Property<int>("IllustrationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductModelId")
                        .HasColumnType("int");

                    b.HasKey("ProductModelIllustrationId");

                    b.HasIndex("IllustrationId");

                    b.HasIndex("ProductModelId");

                    b.ToTable("ProductModelIllustration", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductModelProductDescriptionCulture", b =>
                {
                    b.Property<int>("ProductModelProductDescriptionCultureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductModelProductDescriptionCultureId"));

                    b.Property<string>("CultureId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductDescriptionId")
                        .HasColumnType("int");

                    b.Property<int>("ProductModelId")
                        .HasColumnType("int");

                    b.HasKey("ProductModelProductDescriptionCultureId");

                    b.HasIndex("CultureId");

                    b.HasIndex("ProductDescriptionId");

                    b.HasIndex("ProductModelId");

                    b.ToTable("ProductModelProductDescriptionCulture", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductPhoto", b =>
                {
                    b.Property<int>("ProductPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductPhotoId"));

                    b.Property<byte?>("LargePhoto")
                        .HasColumnType("tinyint");

                    b.Property<string>("LargePhotoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<byte?>("ThumbNailPhoto")
                        .HasColumnType("tinyint");

                    b.Property<string>("ThumbnailPhotoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductPhotoId");

                    b.ToTable("ProductPhoto", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductProductPhoto", b =>
                {
                    b.Property<int>("ProductProductPhotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductProductPhotoId"));

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Primary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("ProductPhotoId")
                        .HasColumnType("int");

                    b.HasKey("ProductProductPhotoId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductPhotoId");

                    b.ToTable("ProductProductPhoto", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductReview", b =>
                {
                    b.Property<int>("ProductReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductReviewId"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReviewDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductReviewId");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductReview", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductSubcategory", b =>
                {
                    b.Property<int>("ProductSubcategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductSubcategoryId"));

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductCategoryId")
                        .HasColumnType("int");

                    b.Property<Guid>("Rowguid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ProductSubcategoryId");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("ProductSubcategory", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ScrapReason", b =>
                {
                    b.Property<short>("ScrapReasonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("ScrapReasonId"));

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScrapReasonId");

                    b.ToTable("ScrapReason", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.TransactionHistory", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceOrderLineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("TransactionId");

                    b.HasIndex("ProductId");

                    b.ToTable("TransactionHistory", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.TransactionHistoryArchive", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransactionId"));

                    b.Property<decimal>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceOrderId")
                        .HasColumnType("int");

                    b.Property<int>("ReferenceOrderLineId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("TransactionId");

                    b.ToTable("TransactionHistoryArchive", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.UnitMeasure", b =>
                {
                    b.Property<string>("UnitMeasureCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UnitMeasureCode");

                    b.ToTable("UnitMeasure", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderQty")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<short?>("ScrapReasonId")
                        .HasColumnType("smallint");

                    b.Property<int>("ScrappedQty")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StockedQty")
                        .HasColumnType("int");

                    b.HasKey("WorkOrderId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ScrapReasonId");

                    b.ToTable("WorkOrder", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.WorkOrderRouting", b =>
                {
                    b.Property<short>("OperationSequence")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<short>("OperationSequence"));

                    b.Property<decimal?>("ActualCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ActualEndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ActualResourceHrs")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ActualStartDate")
                        .HasColumnType("datetime2");

                    b.Property<short>("LocationId")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("PlannedCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledEndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledStartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("OperationSequence");

                    b.HasIndex("LocationId");

                    b.HasIndex("ProductId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderRouting", "Production");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.BillOfMaterials", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "ProductAssembly")
                        .WithMany("BillOfMaterials")
                        .HasForeignKey("ProductAssemblyId");

                    b.HasOne("AdventureWorks.Model.Domain.Production.UnitMeasure", "UnitMeasure")
                        .WithMany()
                        .HasForeignKey("UnitMeasureCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductAssembly");

                    b.Navigation("UnitMeasure");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Product", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.ProductModel", "ProductModel")
                        .WithMany("Products")
                        .HasForeignKey("ProductModelId");

                    b.HasOne("AdventureWorks.Model.Domain.Production.ProductSubcategory", null)
                        .WithOne("Products")
                        .HasForeignKey("AdventureWorks.Model.Domain.Production.Product", "ProductSubcategoryId");

                    b.Navigation("ProductModel");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductCostHistory", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("ProductCostHistory")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductDocument", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Document", "DocumentNodeNavigation")
                        .WithMany("ProductDocuments")
                        .HasForeignKey("DocumentNodeNavigationDocumentNode");

                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentNodeNavigation");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductInventory", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Location", "Location")
                        .WithMany("ProductInventories")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("ProductInventories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductListPriceHistory", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("ProductListPriceHistory")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductModelIllustration", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Illustration", "Illustration")
                        .WithMany("ProductModelIllustrations")
                        .HasForeignKey("IllustrationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.ProductModel", "ProductModel")
                        .WithMany("ProductModelIllustrations")
                        .HasForeignKey("ProductModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Illustration");

                    b.Navigation("ProductModel");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductModelProductDescriptionCulture", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Culture", "Culture")
                        .WithMany("ProductModelProductDescriptionCultures")
                        .HasForeignKey("CultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.ProductDescription", "ProductDescription")
                        .WithMany()
                        .HasForeignKey("ProductDescriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.ProductModel", "ProductModel")
                        .WithMany("ProductModelProductDescriptionCultures")
                        .HasForeignKey("ProductModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Culture");

                    b.Navigation("ProductDescription");

                    b.Navigation("ProductModel");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductProductPhoto", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("ProductProductPhotos")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.ProductPhoto", "ProductPhoto")
                        .WithMany("ProductProductPhotos")
                        .HasForeignKey("ProductPhotoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductPhoto");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductReview", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("ProductReviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductSubcategory", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.ProductCategory", "ProductCategory")
                        .WithMany("ProductSubcategories")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductCategory");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.TransactionHistory", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("TransactionHistories")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.WorkOrder", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.ScrapReason", "ScrapReason")
                        .WithMany("WorkOrders")
                        .HasForeignKey("ScrapReasonId");

                    b.Navigation("Product");

                    b.Navigation("ScrapReason");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.WorkOrderRouting", b =>
                {
                    b.HasOne("AdventureWorks.Model.Domain.Production.Location", "Location")
                        .WithMany("WorkOrderRoutings")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.Product", "Product")
                        .WithMany("WorkOrderRoutings")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdventureWorks.Model.Domain.Production.WorkOrder", "WorkOrder")
                        .WithMany("WorkOrderRoutings")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Product");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Culture", b =>
                {
                    b.Navigation("ProductModelProductDescriptionCultures");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Document", b =>
                {
                    b.Navigation("ProductDocuments");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Illustration", b =>
                {
                    b.Navigation("ProductModelIllustrations");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Location", b =>
                {
                    b.Navigation("ProductInventories");

                    b.Navigation("WorkOrderRoutings");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.Product", b =>
                {
                    b.Navigation("BillOfMaterials");

                    b.Navigation("ProductCostHistory");

                    b.Navigation("ProductInventories");

                    b.Navigation("ProductListPriceHistory");

                    b.Navigation("ProductProductPhotos");

                    b.Navigation("ProductReviews");

                    b.Navigation("TransactionHistories");

                    b.Navigation("WorkOrderRoutings");

                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductCategory", b =>
                {
                    b.Navigation("ProductSubcategories");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductModel", b =>
                {
                    b.Navigation("ProductModelIllustrations");

                    b.Navigation("ProductModelProductDescriptionCultures");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductPhoto", b =>
                {
                    b.Navigation("ProductProductPhotos");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ProductSubcategory", b =>
                {
                    b.Navigation("Products")
                        .IsRequired();
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.ScrapReason", b =>
                {
                    b.Navigation("WorkOrders");
                });

            modelBuilder.Entity("AdventureWorks.Model.Domain.Production.WorkOrder", b =>
                {
                    b.Navigation("WorkOrderRoutings");
                });
#pragma warning restore 612, 618
        }
    }
}
